# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b921994f55067d1e86418487d2914a5ecead6bd2c95b6495f1d1cf31ea0434eb2696c51af8a05ba467980dd7eaabd766a960a0a99c4e49d7f60ed97ecc129961

test:
  secret_key_base: 12b0cc66730685ef60b1ac1253f6e46cd114e4961b06999378d7a816ecb3f8abd1fa6b0d9820ee210ae3aa836fedff39840c1560c74242895a5b9d4b9e0f4d27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
